#ifndef SIMULATION_PARAMETERS_H 
#define SIMULATION_PARAMETERS_H

#define NUM_EVENT_GENERATORS 1
#define NUM_EVENT_HANDLERS 1

#define NUM_EVENTS_PER_GEN 30
#define TOTAL_NUM_EVENTS (NUM_EVENTS_PER_GEN * NUM_EVENT_GENERATORS) 

#define MAX_ROUND 1000


#endif